steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/backend-jude/app-engine-tmp', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/backend-jude/app-engine-tmp']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'backend-jude', '--image', 'asia.gcr.io/backend-jude/app-engine-tmp', '--region', 'us-central1']
images:
- asia.gcr.io/backend-jude/app-engine-tmp