steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/backend-jude/asia.gcr.io/backend-jude/', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/backend-jude/asia.gcr.io/backend-jude/']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'backend-jude', '--image', 'gcr.io/backend-jude/asia.gcr.io/backend-jude/', '--region', 'us-central1']
images:
- gcr.io/backend-jude/asia.gcr.io/backend-jude/